licence: "LICENCE_KEY"  

  ########################
  # SERVER CONFIGURATION #
  ########################

database:
  sql:
    enable: "false"
  mongo:
    enable: "false"
    
default-elos: 1200
 
join-message:
  enabled: "true"
  message: "&a%player% &bis now online. &a%currentlyOnline%&7/&c%maxSlots%"
leave-message:
  enabled: "true"
  message: "&c%player% &bis now offline."
motd: 
  whitelist:
    1: "&3Bawz &7| &bPractice"
    2: "&cCurrently under whitelist!"
  unwhitelist:
    1: "&3bawz &7| &bPractice"
    2: "&aFollow @BawzNet!"
maxslots: 2023
  
  #########
  # ITEMS #
  #########
  
spawn-items:
  0:
    material: "IRON_SWORD"
    displayname: "&3Casual"
    command: "/casual"
  1:
    material: "DIAMOND_SWORD"
    displayname: "&5Ranked"
    command: "/ranked"
  2:
    material: "AIR"
    displayname: "null"
    command: "null"
  3:
    material: "AIR"
    displayname: "null"
    command: "null"
  4:
    material: "NAME_TAG"
    displayname: "&3Party"
    command: "/party create"
  5:
    material: "AIR"
    displayname: "null"
    command: "null"
  6:
    material: "AIR"
    displayname: "null"
    command: "null"
  7:
    material: "REDSTONE"
    displayname: "&3Settings"
    command: "/settings"
  8:
    material: "BOOK"
    displayname: "&3Editor"
    command: "/editor"

queue-items:
  0:
    material: "AIR"
    displayname: "null"
    command: "null"
  1:
    material: "AIR"
    displayname: "null"
    command: "null"
  2:
    material: "AIR"
    displayname: "null"
    command: "null"
  3:
    material: "AIR"
    displayname: "null"
    command: "null"
  4:
    material: "AIR"
    displayname: "null"
    command: "null"
  5:
    material: "AIR"
    displayname: "null"
    command: "null"
  6:
    material: "AIR"
    displayname: "null"
    command: "null"
  7:
    material: "AIR"
    displayname: "null"
    command: "null"
  8:
    material: "PACKED_ICE"
    displayname: "&cLeave queue."
    command: "/leavequeue"
    
    #############
    # INVENTORY #
    #############
# Be aware that inventory sizes are only calculated by 9 (example 9+9 = 18) #
inventory:
  automatic-calcul-size: "true"
  casual:
    name: "&8Casual Queue:"
    size: 9
    lore:
      - "&3Queueing&7: &f%inQueue%"
      - "&5Fighting&7: &f%inFight%"
  ranked:
    name: "&8Ranked Queue:"
    size: 9
    lore:
      - "&3Queueing&7: &f%inQueue%"
      - "&5Fighting&7: &f%inFight%"
      
    ###############
    # PERMISSIONS #
    ###############
    
permissions:
  ladder: "bawz.ladder"
  arena: "bawz.arena"
  locations: "bawz.location"
  
    ############
    # MESSAGES #
    ############
    
messages:
  no-permissions: "&cYou don't have the permissions!"
  ladder-already-exist: "&cThis ladder already exists!"
  ladder-doesnt-exist: "&cThe ladder: &f%ladderName% &cdoesn't exists!"
  created-ladder: "&aThe ladder: &f%ladderName% &awas created in &f%ladderType%&a!"
  ladder-type-doesnt-exist: "&cThe ladder types currently available are: &3normal&7, &3uhc&7, &3sumo&7, &3hcf&7, &3spleef&7, &3bridges&7, &3combo!"
  ladder-help:
    - ""
    - "§5Ladders Command:"
    - ""
    - "§d/ladder create <name> <type>"
    - "§d/ladder setinv <name>"
    - "§d/ladder seticon <name>"
    - "§d/ladder seteditable <name> <true/false>"
    - "§d/ladder setslots <name> <number>"
    - "§d/ladder setdisplay <name> <displayName>"
  arena-help:
    - ""
    - "§5Arena Command:"
    - ""
    - "§d/arena create <name> <type>"
    - "§d/arena setloc<1/2> <name>"
  arena-not-exist: "&cThis arena does not exist!"
  arena-location: "&aYou have well defined the %locationSet% position"
  arena-created: "&aYou have created the arena: %arenaName% in the type: %arenaType%"
  arena-already-exist: "&cThis arena already exists!"
  enter-in-queue: "&aYou have joined the queue in the ladder: %ladderName% in the type: %queueType%"
  leave-queue: "&cYou have been left the queue!"
  
  #################
  # MATCH MESSAGE #
  #################
  
  kill-message: "&3%killer% to kill &d%killed%"
  match-found: "&7* &fA opponent was found! It's about &3%opponent%&f!"
  countdown-message: "&3Match starting in &f%countdown% seconds!"
  inventories-message: 
    - ""
    - "&3%winner% &fhave won the match! &dInventories&7: &a%winnerInventories%&7, &c%looserInventories%&7."
  match-started: "&fThe match has been begin!"
  
  #######################
  # MATCH CONFIGURATION #
  #######################
  
#The result can only be calculated in second grade!#
respawn-after-match-time: 10
  
  #############
  # LOCATIONS #
  #############
locations:
  spawn:
  editor: