licence: "kezuk"  

  ########################
  # SERVER CONFIGURATION #
  ########################

database:
  sql:
    enable: "false"
  mongo:
    enable: "false"
    
default-elos: 1200

join-message:
  enabled: "false"
  message: "&e%player% &fis now online. &6%currentlyOnline%&7/&6%maxSlots%"
leave-message:
  enabled: "false"
  message: "&c%player% &bis now offline."
motd: 
  whitelist:
    1: " &e&lOGPOT.GG &7│ &6Practice"
    2: " &cCurrently whitelisted!"
  unwhitelist:
    1: "&eOGPOT &7│ &6Practice"
    2: "&eFollow @OGPOTGG!"
maxslots: 2023

color:
  enable: "GREEN"
  disable: "RED"
  
displayer:
  enable: "ON"
  disable: "OFF" 
   
  #########
  # ITEMS #
  #########
  
spawn-items:
  0:
    material: "IRON_SWORD"
    material-id: 0
    displayname: "&eCasual"
    command: "/casual"
  1:
    material: "DIAMOND_SWORD"
    material-id: 0
    displayname: "&eRanked"
    command: "/ranked"
  4:
    material: "NAME_TAG"
    material-id: 0
    displayname: "&eParty"
    command: "/party create"
  7:
    material: "REDSTONE"
    material-id: 0
    displayname: "&eSettings"
    command: "/settings"
  8:
    material: "BOOK"
    material-id: 0
    displayname: "&eEditor"
    command: "/editor"

queue-items:
  8:
    material: "PACKED_ICE"
    material-id: 0
    displayname: "&cLeave queue."
    command: "/leavequeue"
    
    #############
    # INVENTORY #
    #############
# Be aware that inventory sizes are only calculated by 9 (example 9+9 = 18) #
inventory:
  merge-casual-and-ranked: true
  automatic-calcul-size: "true"
  merge:
    name: "&eChoose mode:"
    size: 9
    items:
     0:
      displayname: "&eUnranked"
      material: "IRON_SWORD"
      material-id: 0
      commands: "/unranked"
      lore: 
        - ""
        - "&7test"
        - ""
     1:
      displayname: "&6Ranked"
      material: "DIAMOND_SWORD"
      material-id: 0
      commands: "/ranked"
      lore:
        - ""
        - "&8test"
        - ""
  casual:
    name: "&eCasual Queue:"
    size: 9
    lore:
      - "&7⚠ │&eQueueing: &f%inQueue%"
      - "&7⚠ │&eFighting: &f%inFight%"
  ranked:
    name: "&eRanked Queue:"
    size: 9
    lore:
      - "&7? │&eQueueing: &f%inQueue%"
      - "&7? │&eFighting: &f%inFight%"
      
  settings:
    name: "&eSettings:"
    size: 9
    items:
      0:
       displayname: "&dScoreboard &7[%sbStatus%&7]"
       material: "PAINTING"
       material-id: 0
       command: "/scoreboard"
       lore:
        - ""
        - "&7Change the scoreboard display!"
        - ""
      
  preview:
    name: "&7Preview of: &c%playerName%"
    size: 54
    items:
      playerinformation:
        material: "MELON"
        data: 0
        name: "&7⚠ │ &ePlayer Informations"
        lore: 
          - " "
          - " §eFood: f%foodLevel%"
          - " §eHearts: f%lifeLevel%"
          - " §eHits: §f%hits%"
          - " §eLongest Combo: f%longestCombo%"
      potion:
        material: "POTION"
        data: 16421
        name: "&7⚠ │ &ePotion:"
        lore:
          - " "
          - " §eRemaining: §f%amountPot%"
          - " §eAccuracy: §f%accuracyPot%"
          - " §eMissed: §f%missedPot%"
      
      
    ###############
    # PERMISSIONS #
    ###############
    
permissions:
  ladder: "bawz.ladder"
  arena: "bawz.arena"
  locations: "bawz.location"
  
    ############
    # MESSAGES #
    ############
    
messages:
  no-permissions: "&cYou don't have the permissions!"
  ladder-already-exist: "&cThis ladder already exists!"
  ladder-doesnt-exist: "&cThe ladder: &f%ladderName% &cdoesn't exists!"
  created-ladder: "&aThe ladder: &f%ladderName% &awas created in &f%ladderType%&a!"
  ladder-type-doesnt-exist: "&cThe ladder types currently available are: &3normal&7, &3uhc&7, &3sumo&7, &3hcf&7, &3spleef&7, &3bridges&7, &3combo!"
  ladder-help:
    - ""
    - "§eLadders Command:"
    - ""
    - "§e/ladder create <name> <type>"
    - "§e/ladder setinv <name>"
    - "§e/ladder seticon <name>"
    - "§e/ladder seteditable <name> <true/false>"
    - "§e/ladder setslots <name> <number>"
    - "§e/ladder setdisplay <name> <displayName>"
    - "§e/ladder setcooldownpearl <name> <true/false>"
    - "§e/ladder setcooldowntime <name> <seconds>"
  arena-help:
    - ""
    - "§eArena Command:"
    - ""
    - "§e/arena create <name> <type>"
    - "§e/arena setloc<1/2> <name>"
  arena-not-exist: "&cThis arena does not exist!"
  arena-location: "&aYou have well defined the %locationSet% position"
  arena-created: "&aYou have created the arena: %arenaName% in the type: %arenaType%"
  arena-already-exist: "&cThis arena already exists!"
  enter-in-queue: "&aYou have joined the queue in the ladder: %ladderName% in the type: %queueType%"
  leave-queue: "&cYou have been left the queue!"
  not-in-queue: "&cYou're not in queue at this moment!"
  
  #################
  # MATCH MESSAGE #
  #################
  
  match:
    cannot-launch-enderpearl: "&cYou cannot use this now!"
    cooldown-enderpearl: "&3You can launch this in &f%cooldown%&bseconds"
    found: "&7⚠│ &fopponent found: &4%opponent%!"
    countdown: "&eMatch starting in &f%countdown% seconds!"
    kill: "&e%killer% &fkilled &e%killed%"
    winner: "&e%winner% &fwon!"
    inventories: "&eInventories:"
    begin: "&fThe match start!"
  
  #######################
  # MATCH CONFIGURATION #
  #######################
  
#The result can only be calculated in second grade!#
respawn-after-match-time: 10
  
  #############
  # LOCATIONS #
  #############
locations:
  spawn:
  editor: