licence: "LICENCE_KEY"  

  ########################
  # SERVER CONFIGURATION #
  ########################

database:
  sql:
    enable: "false"
  mongo:
    enable: "false"
    
default-elos: 1200

join-message:
  enabled: "true"
  message: "&a%player% &bis now online. &a%currentlyOnline%&7/&c%maxSlots%"
leave-message:
  enabled: "true"
  message: "&c%player% &bis now offline."
motd: 
  whitelist:
    1: "&3Bawz &7| &bPractice"
    2: "&cCurrently under whitelist!"
  unwhitelist:
    1: "&3bawz &7| &bPractice"
    2: "&aFollow @BawzNet!"
maxslots: 2023

color:
  enable: "GREEN"
  disable: "RED"
  
displayer:
  enable: "ON"
  disable: "OFF" 
   
  #########
  # ITEMS #
  #########
  
spawn-items:
  0:
    material: "IRON_SWORD"
    material-id: 0
    displayname: "&3Casual"
    command: "/casual"
  1:
    material: "DIAMOND_SWORD"
    material-id: 0
    displayname: "&5Ranked"
    command: "/ranked"
  4:
    material: "NAME_TAG"
    material-id: 0
    displayname: "&3Party"
    command: "/party create"
  7:
    material: "REDSTONE"
    material-id: 0
    displayname: "&3Settings"
    command: "/settings"
  8:
    material: "BOOK"
    material-id: 0
    displayname: "&3Editor"
    command: "/editor"

queue-items:
  8:
    material: "PACKED_ICE"
    material-id: 0
    displayname: "&cLeave queue."
    command: "/leavequeue"
    
    #############
    # INVENTORY #
    #############
# Be aware that inventory sizes are only calculated by 9 (example 9+9 = 18) #
inventory:
  automatic-calcul-size: "true"
  casual:
    name: "&8Casual Queue:"
    size: 9
    lore:
      - "&3Queueing&7: &f%inQueue%"
      - "&5Fighting&7: &f%inFight%"
  ranked:
    name: "&8Ranked Queue:"
    size: 9
    lore:
      - "&3Queueing&7: &f%inQueue%"
      - "&5Fighting&7: &f%inFight%"
      
  settings:
    name: "&8Settings:"
    size: 9
    items:
      0:
       displayname: "&dScoreboard &7[%sbStatus%&7]"
       material: "PAINTING"
       material-id: 0
       command: "/scoreboard"
       lore:
        - ""
        - "&7Change the scoreboard display according to your mood!"
        - ""
      
  preview:
    name: "&7Preview of: &c%playerName%"
    size: 54
    items:
      playerinformation:
        material: "MELON"
        data: 0
        name: "&7* &3Player Informations&7:"
        lore: 
          - " "
          - " §bFood level§7: §f%foodLevel%"
          - " §bLife level§7: §f%lifeLevel%&4♥"
          - " §bHits§7: §f%hits%"
          - " §bLongest Combo§7: §f%longestCombo%"
      potion:
        material: "POTION"
        data: 16421
        name: "&7* &3Potion&7:"
        lore:
          - " "
          - " §3Remaining§7: §f%amountPot%"
          - " §3Accuracy§7: §f%accuracyPot%"
          - " §3Missed§7: §f%missedPot%"
      
      
    ###############
    # PERMISSIONS #
    ###############
    
permissions:
  ladder: "bawz.ladder"
  arena: "bawz.arena"
  locations: "bawz.location"
  
    ############
    # MESSAGES #
    ############
    
messages:
  no-permissions: "&cYou don't have the permissions!"
  ladder-already-exist: "&cThis ladder already exists!"
  ladder-doesnt-exist: "&cThe ladder: &f%ladderName% &cdoesn't exists!"
  created-ladder: "&aThe ladder: &f%ladderName% &awas created in &f%ladderType%&a!"
  ladder-type-doesnt-exist: "&cThe ladder types currently available are: &3normal&7, &3uhc&7, &3sumo&7, &3hcf&7, &3spleef&7, &3bridges&7, &3combo!"
  ladder-help:
    - ""
    - "§5Ladders Command:"
    - ""
    - "§d/ladder create <name> <type>"
    - "§d/ladder setinv <name>"
    - "§d/ladder seticon <name>"
    - "§d/ladder seteditable <name> <true/false>"
    - "§d/ladder setslots <name> <number>"
    - "§d/ladder setdisplay <name> <displayName>"
    - "§d/ladder setcooldownpearl <name> <true/false>"
    - "§d/ladder setcooldowntime <name> <seconds>"
  arena-help:
    - ""
    - "§5Arena Command:"
    - ""
    - "§d/arena create <name> <type>"
    - "§d/arena setloc<1/2> <name>"
  arena-not-exist: "&cThis arena does not exist!"
  arena-location: "&aYou have well defined the %locationSet% position"
  arena-created: "&aYou have created the arena: %arenaName% in the type: %arenaType%"
  arena-already-exist: "&cThis arena already exists!"
  enter-in-queue: "&aYou have joined the queue in the ladder: %ladderName% in the type: %queueType%"
  leave-queue: "&cYou have been left the queue!"
  not-in-queue: "&cYou're not in queue at this moment!"
  
  #################
  # MATCH MESSAGE #
  #################
  
  match:
    cannot-launch-enderpearl: "&cYou cannot use this now!"
    cooldown-enderpearl: "&3You can launch this in &f%cooldown%&bseconds"
    found: "&7* &fA opponent was found! It's about &3%opponent%&f!"
    countdown: "&3Match starting in &f%countdown% seconds!"
    kill: "&3%killer% to kill &d%killed%"
    winner: "&3%winner% &fhave won the match!"
    inventories: "&bInventories &7(Click to open)&f:"
    begin: "&fThe match has been begin!"
  
  #######################
  # MATCH CONFIGURATION #
  #######################
  
#The result can only be calculated in second grade!#
respawn-after-match-time: 10
  
  #############
  # LOCATIONS #
  #############
locations:
  spawn:
  editor: